# Generated by Django 5.1.1 on 2024-10-06 15:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("personal_accident", "Personal Accident"),
                            ("health", "Health Insurance"),
                            ("life", "Life Insurance"),
                            ("home", "Home Insurance"),
                            ("travel", "Travel Insurance"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cover",
                    models.DecimalField(
                        decimal_places=2, default=200000, max_digits=12
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("quoted", "Quoted"),
                            ("accepted", "Accepted"),
                            ("bound", "Bound"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicyStateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("quoted", "Quoted"),
                            ("accepted", "Accepted"),
                            ("bound", "Bound"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_history",
                        to="insurance.policy",
                    ),
                ),
            ],
        ),
    ]
