# Generated by Django 5.1.1 on 2024-10-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="state",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("quoted", "Quoted"),
                    ("accepted", "Accepted"),
                    ("bound", "Bound"),
                    ("active", "Active"),
                    ("declined", "Declined"),
                    ("expired", "Expired"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="policystatehistory",
            name="state",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("quoted", "Quoted"),
                    ("accepted", "Accepted"),
                    ("bound", "Bound"),
                    ("active", "Active"),
                    ("declined", "Declined"),
                    ("expired", "Expired"),
                ],
                max_length=20,
            ),
        ),
    ]
